version: '3'
services:

  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    environment:
      # See https://ghost.org/docs/concepts/config/ for variables
      compress: y # If using nginx compression you can change this to n
      url: https://blog.example.com # Blog base url EDIT
      database__client: mysql
      database__connection__host: db # db means the host is the db container below
      database__connection__user: YOUR_DB_USER # db user same as below
      database__connection__password: YOUR_DB_PASSWORD # db password same as below
      database__connection__database: YOUR_DB_NAME # db name same as below
      mail__transport: SMTP #99.9% you dont need to change this
      # See https://github.com/nodemailer/nodemailer/tree/0.7/#well-known-services-for-smtp for options & uncomment
      # mail__options__service: mail.nayefalebrahim.com
      # If service is on the list remove host, port, secureConnection lines. Just specify user & pass
      mail__options__host: mail.example-server.com
      mail__options__port: 465
      mail__options__secureConnection: y # Change to n if your server does not support encryption
      mail__options__auth__user: YOUR_USER_CREDENTIAL # SMTP username
      mail__options__auth__pass: YOUR_PASSWORD # SMTP password
      # Change Joe Smith to your custom Sender name, and noreply@example.com to custom mail
      # Keep the brackets and single quotes
      mail__from: "'Joe Smith' <noreply@example.com>" 
      # This maps your container to your host to persist data
      # Aka data will not be lost when rebuilding
      # /opt/ghost_content on the host - create the directory & change if needed
      # /var/lib/ghost/content on the container - don't change
    volumes:
      - ./ghost_content:/var/lib/ghost/content

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASS # set a new root password unique
      MYSQL_DATABASE: nae_ghost # set a db name same as above
      MYSQL_USER: nae_ghost # set a db user same as above
      MYSQL_PASSWORD: 9EH246EGy#gKK # set a db password same as above
      # This maps your container to your host to persist data
      # Aka data will not be lost when rebuilding
      # /opt/ghost_mysql on the host - create the directory & change if needed
      # /var/lib/mysql on the container - don't change
    volumes:
      - ./ghost_mysql:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
      # This maps your container to your host to persist data
      # Aka data will not be lost when rebuilding
    volumes:
      # needed for letsencrypt
      # Download certbot https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx.html
       - /etc/letsencrypt/:/etc/letsencrypt/
       - /usr/share/nginx/html:/usr/share/nginx/html
       # logs so fail2ban can use if installed
       - /var/log/nginx:/var/log/nginx
       # Change this if needed
       - ./ghost_content:/var/www/ghost
